//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaHesabi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kul_bnk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kul_bnk()
        {
            this.tbl_kullanicihareket = new HashSet<tbl_kullanicihareket>();
        }
    
        public byte id { get; set; }
        public Nullable<byte> kullaniciid { get; set; }
        public Nullable<byte> bankaid { get; set; }
        public string iban { get; set; }
        public string hesapno { get; set; }
    
        public virtual tbl_Banka tbl_Banka { get; set; }
        public virtual tbl_kullanici tbl_kullanici { get; set; }

     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kullanicihareket> tbl_kullanicihareket { get; set; }
    }
}
