//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaHesabi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Banka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Banka()
        {
            this.tbl_kul_bnk = new HashSet<tbl_kul_bnk>();
        }
    
        public byte id { get; set; }
        public string bankaad { get; set; }
        public string bankakod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kul_bnk> tbl_kul_bnk { get; set; }
    }
}
