//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaHesabi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kullanicihareket
    {
        public byte id { get; set; }
        public Nullable<byte> alici_klnciid { get; set; }
        public Nullable<byte> alici_bnkid { get; set; }
        public string harekettur { get; set; }
        public decimal miktar { get; set; }
        public Nullable<byte> gon_klncid { get; set; }
        public Nullable<byte> gon_bnkid { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual tbl_kul_bnk tbl_kul_bnk { get; set; }
        public virtual tbl_kullanici tbl_kullanici { get; set; }
        public virtual tbl_kullanici tbl_kullanici1 { get; set; }
    }
}
